# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Upsun (formerly Platform.sh).
# More information: https://docs.upsun.com/routes/
"https://{default}/":
  type: upstream
  upstream: "art-creation:http"

# A basic redirect definition
# More information: https://docs.upsun.com/routes/examples/redirect/
"https://www.{default}":
  type: redirect
  to: "https://{default}/"
