# .platform/app.yaml
name: app
type: php:8.2   # Version PHP utilisée
disk: 1024       # Espace disque alloué à l'application

# Relations avec les services (ici MySQL)
relationships:
    database: "mysql:mysql"

# Build et déploiement
hooks:
    build: |
        # Composer install
        composer install --no-dev --optimize-autoloader
